# Generated by Django 4.0.2 on 2022-03-30 20:24

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 30, 20, 24, 31, 988661, tzinfo=utc)),  # noqa: E501
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='contactus',
            name='raw_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(choices=[('PB', 'PrivatBank'), ('MB', 'MonoBank'), ('OB', 'OschadBank')], max_length=64),  # noqa: E501
        ),
    ]
