# Generated by Django 4.0.2 on 2022-03-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_contactus_created_contactus_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='raw_content',
            field=models.TextField(),
        ),
    ]
